AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Simple SpringBoot + Kotlin example using Api proxy.
Resources:
  hello:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: se.tnos.serverlesslab.hello.StreamLambdaHandler
      CodeUri: ./target/serverless-kotlin-api-0.0.1-SNAPSHOT-aws.jar
      Runtime: java8
      Timeout: 60
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any